fix: Remove static keyword from ActionExecuteFile definition
Fixed compilation error where ActionExecuteFile was declared as non-static
in action.h but defined as static in action.c.

Error fixed:
  action.c:6858:1: error: static declaration of 'ActionExecuteFile' follows
  non-static declaration

The function needs to be non-static so it can be called from ImportAction.cpp
to process imported schematic data.